openapi: '3.0.2'
info:
  title: 그랩 테스트
  version: 1.0.0
  description: 오픈api 테스트
servers:
  - url: https://tnuubhsp5e.execute-api.ap-northeast-2.amazonaws.com/dev
    description: Development API Test server

components:
  schemas:
    class:
      type: object
      properties:
        teacherName:
          type: string
        teacherImage:
          type: string
        classId:
          type: integer
        subjectTitle:
          type: string
        currentLevel:
          type: integer
    GeneralError:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
  
paths:
  /class:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/class'
