openapi: '3.0.2'
info:
  title: 그랩 테스트
  version: 1.0.0
  description: 오픈api 테스트입니다.^^ㅎㅎ
servers:
  - url: https://tnuubhsp5e.execute-api.ap-northeast-2.amazonaws.com/dev
    description: Development API Test server

components:
  schemas:
    GeneralError:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
  
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
